### ISSUE TITLE
Managed hosting?

### ISSUE THREAD

**Issue by colinodell** [philsturgeon/phpversions.info#236]
What are your thoughts on adding a section for managed hosting?

For example, my employer primarily does managed VPS hosting - we handle everything for clients who don't have the expertise or time to configure the OS, install packages, tweak performance, install security updates, upgrade their CMS/framework, etc.  We support PHP 7.0.3 but don't fit under the umbrella of Shared Hosting or PaaS.

Would you be interested in adding a section for managed hosts or would you prefer sticking with "self-service" providers?

**Comment by philsturgeon** [comment]
Managed Hosting would make sense. 

What im trying to avoid is the types of provider that let you do whatever you want, because if you've just got an empty server and are in charge of "doing stuff" then it's pretty tough to say what version "they" are providing. 

Seeing as Managed Hosting has a "they" (you) I expect that it could fit into this system.

I was wondering about merging pass and shared files into one mega hosts.yml and having a type attribute as they aren't different enough to warrant multiples. There certainly wouldn't be much point in making a third managed.yml.

Fancy doing a PR and shoving your company in as the first ones? That might be a little reward for spending the time merging em. :D 

If you get stuck gimme a busted PR and I'll fix it up.

**Comment by colinodell** [comment]
Alright I think I've got it working - see #237

**Comment by philsturgeon** [comment]
Impressive turnaround!

**Comment by colinodell** [comment]
Thanks!  I've been wanting to play more with Jekyll and Ruby, so this was a nice light introduction :)
