### ISSUE TITLE
Should CLI versions be mentioned?

### ISSUE THREAD

**Issue by johnRivs** [philsturgeon/phpversions.info#31]
Because 1and1 for example gives you php4.4.9 or something around that when you connect via SSH.

**Comment by markoheijnen** [comment]
By default it also uses the CGI version but we do have CLI if requested. Will check with our operation team to see if we can change this safely without possible breakage.

**Comment by philsturgeon** [comment]
Why on earth is PHP 4.anything available anywhere? 

Also, it really confuses me that the PHP CLI and CGI versions are different. I know how its possibly, but I don't know why that is the case anywhere.

**Comment by markoheijnen** [comment]
That is my more or less my response too. It's all about possible breakage and the amount of customers still using it. How bigger the company, how bigger the problem.

Our CLI/CGI versions aren't different. We do support both since we always had CGI and not CLI. Again unsure if that can be changed or not.

**Comment by philsturgeon** [comment]
Thanks for the input on this and sorry for the delay. While I accept this does happen, I really hope it's not common enough for us to have to factor it in right now.

I'm going to keep acting like hosts are offering the same version on both for now, until it bites us in the ass. 

Cheers all.
