### ISSUE TITLE
beta versions not updated by bin/update-versions

### ISSUE THREAD

**Issue by jsamuel** [philsturgeon/phpversions.info#327]
The `bin/update-versions` script is unable to update PHP beta versions (and likely release candidate versions) due to the format of PHP beta release version numbers not being valid semantic versioning according to `vendor/naneau/semver/src/Naneau/SemVer/Regex.php`.

```
$ php7.0-sp bin/update-versions

...

Parsing ServerPilot PHP 71 from: http://php71.serverpilot-phpversions.info/
-- ERROR: Failed to parse ServerPilot

"7.1.0beta3" is not a valid SemVer
```

**Comment by philsturgeon** [comment]
This seems like something I won’t be able to fix for a bit, its been sat in my inbox for ages. Can you help me?


On August 22, 2016 at 2:00:12 PM, Justin Samuel (notifications@github.com) wrote:

The bin/update-versions script is unable to update PHP beta versions (and likely release candidate versions) due to the format of PHP beta release version numbers not being valid semantic versioning according to vendor/naneau/semver/src/Naneau/SemVer/Regex.php.

$ php7.0-sp bin/update-versions

...

Parsing ServerPilot PHP 71 from: http://php71.serverpilot-phpversions.info/
-- ERROR: Failed to parse ServerPilot

"7.1.0beta3" is not a valid SemVer

**Comment by philsturgeon** [comment]
Fixed! https://github.com/philsturgeon/phparse/blob/13fc38986a7a389f5015040ac4b49b7fcf192ab5/src/Info.php#L18

**Comment by jsamuel** [comment]
Thanks for fixing this! Definitely will be helpful when PHP 7.2 arrives.
